apiVersion: apps/v1
kind: Deployment
metadata:
  name: productsbackend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: productsbackend
  template:
    metadata:
      labels:
        app: productsbackend
    spec:
      containers:
        - name: productsbackend
          image: nathanseixeiro/products:v2
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_URLS
              value: http://*:80

---
apiVersion: v1
kind: Service
metadata:
  name: productsbackend
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32001
  selector:
    app: productsbackend
