version: '3.4'

services:

    frontend:
        image: store:latest
        build:
            context: .
            dockerfile: ./Store/Dockerfile
        environment:
           - ProductEndpoint=http://backend:8080
        ports:
           - "32000:8080"
        depends_on:
           - backend
    backend:
        image: product:latest
        build:
            context: .
            dockerfile: ./Products/Dockerfile
        ports:
           - "32001:8080"